# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: https://tmayer18.github.io/tmayer.github.io/

# Title of the Site
title: Timothy Mayer
# Description of the Site
description: Engineering Portfolio
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Portfolio, Tim Mayer
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: tmayer18@aol.com
# facebook_username: thedevslot
# twitter_username: thedevslot
# instagram_username: thedevslot
linkedin_username: https://www.linkedin.com/in/timothy-mayer-3b3b7b16b/
github_username:  tmayer18
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Timothy Mayer
# URL for the Image of the Author
author-image: assets/images/headshot.jpg
# 60 Words About the Author
author-about: A Robotics and Controls Engineer, currently pursuing a Master's Degree in Mechanical Engineering at Carnegie Mellon University. After graduation in May 2024, I look to pursue an exciting job in the field robotics or controls, utilizing my skills in mechatronics, system controls, and system design.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/timothy-mayer-3b3b7b16b/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

  -
    scope:
      type: 'projects'
      path: ''
    values:
      layout: 'project' # all _projects collection members use this layout by default

# Collections
collections:
  projects:
    output: true

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
